# [70] Pandasㅣ3-DataFrame 자료형

##### 💡 DataFrame : 행, 열로 구성

- DataFrame 생성 방법 2가지

| 파이썬 자료형을 변환 | ● 2차원 리스트 (행, 열) <br> ● 리스트를 원소로 갖는 딕셔너리 <br> ● 딕셔너리를 원소로 갖는 리스트 |
| :-- | :-- |
| **수집된 데이터로부터 생성** | ● **csv 파일로부터 가져오기 (쉼표로 구분)** <br> ● **엑셀 파일(*. xlsx)로부터 가져오기** <br> ● **데이터베이스로부터 가져오기 (SQL)** <br> ● **웹 데이터 수집 (OpenAPI 연동, 웹 크롤링)** <br> &nbsp;&nbsp;&nbsp; → **웹에서 수집한 데이터의 경우 딕셔너리를 원소로 갖는 리스트로 정리 후 DataFrame으로 변환** |

### 1. 패키지 설치

In [ ]:
# 엑셀 파일 처리를 위한 패키지 설치
!pip install --upgrade openpyxl xlrd

Requirement already satisfied: openpyxl in c:\users\sonsa\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: et-xmlfile in c:\users\sonsa\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### 2. 준비작업

In [2]:
# 라이브러리 참조
from pandas import DataFrame, read_csv, read_excel # pandas라이브러리에서 DataFrame, read_csv, read_excel 호출

### 3. DataFrame 생성

##### ① 2차원 리스트 → DataFrame 변환

- 인덱스는 0부터 일련번호로 자동 부여됨

In [ ]:
# 어느 학급의 성적을 표현한 2차원 리스트
grade_data = [
                [1, "남자", 98,  77,  88,  64],
                [2, "여자", 88,  90,  62,  72],
                [1, "남자", 92,  70,  83,  79],
                [3, "여자", 63,  60,  31,  70],
                [4, "남자", 75,  50,  90,  88]
            ]

# 2차원 리스트를 데이터프레임으로 변환
df = DataFrame(grade_data)
df

   0   1   2   3   4   5
0  1  남자  98  77  88  64
1  2  여자  88  90  62  72
2  1  남자  92  70  83  79
3  3  여자  63  60  31  70
4  4  남자  75  50  90  88

In [ ]:
# 인덱스와 컬럼 이름 지정
i_names = ['철수', '영희', '민철', '수현', '호영'] # 인덱스 이름으로 사용할 리스트
c_names = ['학년', '성별', '국어', '영어', '수학', '과학'] # 컬럼 이름으로 사용할 리스트

# 인덱스와 컬럼이름 지정하기
df = DataFrame(grade_data, index=i_names, columns=c_names)
df

    학년  성별  국어  영어  수학  과학
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

##### ② 리스트를 원소로 갖는 딕셔너리 → DataFrame 변환

- 인덱스는 0부터 일련번호로 자동 부여됨
- Series에서는 Key가 index가 됨
- DataFrame에서는 딕셔너리 key가 컬럼(열)이름이 됨

In [ ]:
# 어느 학급의 성적표를 표현한 딕셔너리
grade_dic = {
    '학년': [1, 2, 1, 3, 4],
    '성별': ['남자', '여자', '남자', '여자', '남자'],
    '국어': [98, 88, 92, 63, 75],
    '영어': [77, 90, 70, 60, 50],
    '수학': [88, 62, 83, 31, 90],
    '과학': [64, 72, 79, 70, 88]
}

df = DataFrame(grade_dic) # key는 컬럼(열)이 됨
df

   학년  성별  국어  영어  수학  과학
0   1  남자  98  77  88  64
1   2  여자  88  90  62  72
2   1  남자  92  70  83  79
3   3  여자  63  60  31  70
4   4  남자  75  50  90  88

In [ ]:
# 인덱스와 인덱스 이름을 지정한 DataFrame
df = DataFrame(grade_dic,
               index=['철수', '영희', '민철', '수현', '호영']) # 인덱스 지정

# 인덱스 이름 지정하기
df.index.name = '이름'
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

##### ② 딕셔너리를 원소로 갖는 리스트 → DataFrame 변환

- 인덱스는 0부터 일련번호로 자동 부여됨

In [4]:
grade_list = [
    {"이름": "철수", "학년": 1, "성별": "남자", "국어": 98, "영어": 77, "수학": 88, "과학": 64},
    {"이름": "영희", "학년": 2, "성별": "여자", "국어": 88, "영어": 90, "수학": 62, "과학": 72},
    {"이름": "민철", "학년": 1, "성별": "남자", "국어": 92, "영어": 70, "수학": 83, "과학": 79},
    {"이름": "수현", "학년": 3, "성별": "여자", "국어": 63, "영어": 60, "수학": 31, "과학": 70},
    {"이름": "호영", "학년": 4, "성별": "남자", "국어": 75, "영어": 50, "수학": 90, "과학": 88}
] # 딕셔너리는 행이 됨

df = DataFrame(grade_list) # key는 컬럼(열)이 됨
df

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

In [ ]:
# 인덱스 이름 지정하기
df.ndex.name =i '인덱스'
df

     이름  학년  성별  국어  영어  수학  과학
인덱스
0    철수   1  남자  98  77  88  64
1    영희   2  여자  88  90  62  72
2    민철   1  남자  92  70  83  79
3    수현   3  여자  63  60  31  70
4    호영   4  남자  75  50  90  88

### 4. 인덱스 다루기

##### ① set_index('컬럼') 메서드 : DataFrame의 특정 컬럼을 index로 지정 (기존 인덱스 → 지정한 컬럼 인덱스로 변경)

In [54]:
# 원본 데이터 프레임 생성 (리스트를 원소로 갖는 딕셔너리 → DataFrame 변환)
grade = {
    "이름": ['철수', '영희', '민철', '수현', '호영'],
    "학년": [1, 2, 1, 3, 4],
    "성별": ['남자', '여자', '남자', '여자', '남자'],
    "국어": [98, 88, 92, 63, 75],
    "영어": [77, 90, 70, 60, 50],
    "수학": [88, 62, 83, 31, 90],
    "과학": [64, 72, 79, 70, 88]
    }

df = DataFrame(grade)
df

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

- set_index('컬럼') 메서드 : 원본은 변화 없고, 변경사항이 저장된 `복사본 리턴`

In [55]:
# set_index('컬럼') 메서드 : DataFrame의 특정 컬럼을 index로 지정하고 복사본 리턴
df_setindex = df.set_index('이름')
df_setindex

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

In [56]:
# df_setindex 복사본을 리턴하여 원본 df는 변화 없음
df

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

- set_index('컬럼', inplace = True) 메서드 : 복사본 리턴 없이 원본에 바로 적용 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; → `원본데이터를 변경하는건 위험하기 때문에 권장 X`

In [57]:
# set_index('컬럼', inplace=True) 메서드 : 복사본 리턴 없이 원본에 바로 적용
df_setindex2 = df.set_index('이름', inplace=True)
df_setindex2

In [58]:
# df_setindex2 복사본 리턴없이 원본에 적용하여 df는 변화 있음
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

##### ② reset_index() 메서드 : 인덱스 해제 (인덱스를 일반 컬럼으로 되돌림)

In [59]:
# 원본 데이터 프레임
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

- reset_index() 메서드 
    - 인덱스를 컬럼으로 되돌린 후 일련번호 형식의 인덱스 새롭게 생성한 `복사본 리턴`하여 원본 변화 없음

In [60]:
# reset_index() : 인덱스 해제 후 복사본 리턴
df_reset = df.reset_index()
df_reset

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

In [61]:
# df_reset 복사본을 리턴하여 원본 df는 변화 없음
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

- reset_index(inplacr=True) 메서드 : 복사본 리턴 없이 원본에 바로 적용 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; → `원본데이터를 변경하는건 위험하기 때문에 권장 X`

In [62]:
# index_reset(inplace=True) 메서드 : 복사본 리턴 없이 원본에 바로 적용
df_reset2 = df.reset_index(inplace=True)
df_reset2

In [63]:
# df_reset2 복사본 리턴없이 원본에 적용하여 df는 변화 있음
df

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

- reset_index() 사용시 주의사항
    - 인덱스를 컬럼으로 되돌린 후 일련번호 형식의 인덱스 새롭게 생성하기 때문에 일려번호 인덱스가 중복

In [68]:
df_reset3 = df.reset_index()
df_reset3

   index  이름  학년  성별  국어  영어  수학  과학
0      0  철수   1  남자  98  77  88  64
1      1  영희   2  여자  88  90  62  72
2      2  민철   1  남자  92  70  83  79
3      3  수현   3  여자  63  60  31  70
4      4  호영   4  남자  75  50  90  88

- reset_index(drop=True) : 기존 인덱스를 제거하고, 일련번호 형식의 인덱스 새롭게 생성

In [77]:
# 원본데이터
df

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

In [ ]:
# '이름'컬럼을 인덱스로 변경하기
df2 = df.set_index('이름')
df2

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

In [ ]:
# reset_index(drop=True) : 기존 인덱스 제거하고 일련번호 형식 인덱스 새롭게 생성
df3 = df2.reset_index(drop=True)
df3 # '이름'컬럼이 삭제됨

   학년  성별  국어  영어  수학  과학
0   1  남자  98  77  88  64
1   2  여자  88  90  62  72
2   1  남자  92  70  83  79
3   3  여자  63  60  31  70
4   4  남자  75  50  90  88

### 5. 외부 파일로부터 데이터 프레임 생성

① CSV 파일을 데이터 프레임으로 가져오기

- pandas의 `read_csv()`함수를 사용
- 로컬에 위치한 파일을 상대,절대 경로 방식으로 가져올 수 있으며 온라인상의 파일을 URL을 기반으로 가져올 수 있음
- CSV파일의 첫 행이 데이터 프레임의 컬럼 이름으로 사용됨
- 인코딩 필요함

In [ ]:
# pandas의 read_csv() 함수를 사용하여 데이터 로드
df = read_csv("https://data.juyounga.kr/data/grade.csv",
              encoding="euc-kr") # 인코딩
df

   이름  학년  성별  국어   영어  수학  과학
0  철수   1  남자  98   77  88  64
1  영희   2  여자  88  120  62  72
2  민철   1  남자  92   70  83  79
3  수현   3  여자  63   60  31  71
4  호영   4  남자  75   50  90  88
5  영호   4  남자  80   88  91  72
6  용식   2  남자  82   88  79  90
7  나영   1  여자  90   92  81  95
8  석영   1  남자  91   90  89  80

In [ ]:
# index_col = '컬럼' : 인덱스로 사용할 열 이름 지정
df = read_csv("https://data.juyounga.kr/data/grade.csv",
              encoding="euc-kr", # 인코딩
              index_col='이름')
df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

② xlsx 파일을 데이터 프레임으로 가져오기
- 인코딩 필요X

In [ ]:
# index_col = '컬럼' : 인덱스로 사용할 열 이름 지정
df = read_excel("https://data.juyounga.kr/data/grade.xlsx",
                index_col='이름') # 인코딩 필요 X
df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80